ACCELERATE_CPU_AFFINITY=1 torchrun --nproc_per_node=8 --nnodes=1  \
    llava/train/train_sdo.py \
    --lora_enable True --lora_r 64 --lora_alpha 128 --mm_projector_lr 5e-7 \
    --deepspeed scripts/zero3.json \
    --model_name_or_path lmms-lab/llava-onevision-qwen2-7b-ov \
    --version qwen_1_5\
    --sdo_alpha_a 1.5 --sdo_alpha_q 1.0 --beta 0.3 --gamma 0 --lamda 10\
    --data_path ./data/labling/7b-sqa-labling/merge_prefQA_7B.json \
    --image_folder ./data/image \
    --video_folder ./data/video \
    --mm_tunable_parts="mm_mlp_adapter,mm_language_model" \
    --mm_vision_tower_lr 5e-7 \
    --vision_tower google/siglip-so400m-patch14-384 \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --group_by_modality_length True \
    --image_aspect_ratio anyres_max_6 \
    --image_grid_pinpoints  "(1x1),...,(6x6)" \
    --mm_patch_merge_type spatial_unpad \
    --bf16 True \
    --run_name sqllava-7b-qwen-lora-sdo-lr5e6-b0.3-apa1.2-lmd10-3epo-v4_sPat_fixVit_prj5e6 \
    --output_dir "./checkpoints/llavaov-7b-qwen-lora-sdo-new1" \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 16 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 400 \
    --save_total_limit 3 \
    --learning_rate 5e-6 \
    --weight_decay 0. \
    --warmup_ratio 0.1 \
    --lr_scheduler_type "linear" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 32768 \
    --gradient_checkpointing True \
    --dataloader_num_workers 6 \
    --lazy_preprocess True \
    --report_to wandb \
    --dataloader_drop_last True \
    --frames_upbound 25 \
