ACCELERATE_CPU_AFFINITY=1 torchrun --nproc_per_node=8 --nnodes=1  \
    llava/train/train_spo.py \
    --lora_enable True --lora_r 64 --lora_alpha 128 --mm_projector_lr 1e-6 \
    --deepspeed scripts/zero3.json \
    --model_name_or_path /mnt/disks/new-disk/Structure-Policy-Optimization/checkpoints/sqllava-qwen-7b-interleave-5e5-0.3sq-30frm \
    --version qwen_1_5\
    --spo_alpha_a 1.5 --spo_alpha_q 1.0 --beta 0.3 --gamma 0 --lamda 10\
    --data_path /mnt/disks/new-disk/data/spo/merge_prefQA_7B_14500_filtered.json \
    --image_folder /mnt/disks/new-disk/LVLM-reasoning/data/m4-instruct \
    --video_folder /mnt/disks/new-disk/LVLM-reasoning/data/sharegptvideo \
    --mm_tunable_parts="mm_mlp_adapter,mm_language_model" \
    --mm_vision_tower_lr 1e-6 \
    --vision_tower google/siglip-so400m-patch14-384 \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --group_by_modality_length True \
    --image_aspect_ratio anyres_max_9 \
    --image_grid_pinpoints  "(1x1),...,(6x6)" \
    --mm_patch_merge_type spatial_unpad \
    --bf16 True \
    --run_name sqllava-7b-qwen-lora-spo-lr1e6-apa1.2-b0.3-lmd10-2epo-prefharderV1 \
    --output_dir "./checkpoints/sqllava-7b-qwen-lora-spo-lr1e6-apa1.2-b0.3-apa1.5-lmd10-2epo-prefharderV1" \
    --num_train_epochs 2 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000000 \
    --save_total_limit 1 \
    --learning_rate 5e-5 \
    --weight_decay 0.05 \
    --warmup_ratio 0.05 \
    --lr_scheduler_type "linear" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 32768 \
    --gradient_checkpointing True \
    --dataloader_num_workers 8 \
    --lazy_preprocess True \
    --report_to wandb \
    --dataloader_drop_last True \
    --frames_upbound 25 \
